FROM debian:bookworm-slim

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    postfix \
    mailutils \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

CMD ["sh", "-c", "postfix start-fg"]
